version: '3.7'

volumes:
    postgres_data:


services:
    postgres_container:
        image: postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: apt_hunter
            PGDATA: /var/lib/postgresql/data/pgdata


    apt_hunter:
        build: .
        volumes:
            - ./logs:/apt_hunter/logs/
        depends_on: 
            - postgres_container
        environment:
            POSTGRES_ADDRESS: postgres_container
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: apt_hunter
            POSTGRES_PORT: 5432

            LOG_PATH: /apt_hunter/logs/

