version: '3.7'

services:
    apt_hunter:
        build: .
        restart: always
        environment:
            # database settings, must match postgres container
            POSTGRES_ADDRESS: postgres_container
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: apt_hunter
            POSTGRES_PORT: 5432


    postgres_container:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: apt_hunter


